#!/usr/bin/env python3
"""
Step 3 of the data pipeline: export the curated rows from restaurants.db into
the repo-root data.js that the static site actually loads.

Emits `const RESTAURANTS = [...]` in the exact schema the page expects:
    name, area, cuisine, price, note, image, url
Only rows with include=1 are exported. Standard library only.
"""

import json
import os
import sqlite3

HERE = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(HERE, "restaurants.db")
DATA_JS = os.path.join(HERE, os.pardir, "data.js")

HEADER = """// AUTO-GENERATED by pipeline/build_data.py — do not edit by hand.
// Restaurant data © OpenStreetMap contributors, licensed under the ODbL
// (https://www.openstreetmap.org/copyright). Regenerate with:
//   python3 pipeline/fetch_osm.py && python3 pipeline/load_db.py && python3 pipeline/build_data.py
//
// Schema per entry: name, area, cuisine, price, note, image, url
// price/note/image are editorial and usually blank (OSM doesn't provide them);
// fill them in the SQLite staging DB for places you want to highlight.
"""

# Field order in each emitted object (matches the site's card renderer).
FIELDS = ["name", "area", "cuisine", "price", "note", "image", "url"]


def main() -> None:
    if not os.path.exists(DB_PATH):
        raise SystemExit(f"{DB_PATH} not found — run pipeline/load_db.py first.")

    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        """
        SELECT name, area, cuisine, price, note, image, website AS url
        FROM places
        WHERE include = 1
        ORDER BY area = '' , area, name
        """
    ).fetchall()
    con.close()

    entries = []
    for r in rows:
        obj = {k: (r[k] or "") for k in FIELDS}
        # json.dumps gives us correctly-escaped JS string literals (valid JS).
        lines = [f"    {k}: {json.dumps(obj[k], ensure_ascii=False)}," for k in FIELDS]
        entries.append("  {\n" + "\n".join(lines) + "\n  }")

    body = "const RESTAURANTS = [\n" + ",\n".join(entries) + "\n];\n"
    if not entries:
        body = "const RESTAURANTS = [];\n"

    with open(DATA_JS, "w", encoding="utf-8") as f:
        f.write(HEADER + "\n" + body)

    print(f"✓ Wrote {len(entries)} restaurants to {os.path.abspath(DATA_JS)}")
    areas = sorted({(r["area"] or "—") for r in rows})
    print(f"  Across {len(areas)} areas. Preview: python3 -m http.server 8000")


if __name__ == "__main__":
    main()
